#include <stdio.h>
#include "listaencadeada.h"

int main() {
    int i;
    printf("\n<<<-Creating a list called l->>>\n");
    list* l = createlist();
    printf("begin -> %p\n", l->begin);
    printf("list_len = %d\n", list_len(l));
    printf("\n<<<-Appending number 10->>>\n");
    append(l, 10);
    print_list(l);
    printf("list_len = %d\n", list_len(l));
    printf("\n<<<-Appending number 20->>>\n");
    append(l, 20);
    print_list(l);
    printf("list_len = %d\n", list_len(l));
    printf("\n<<<-Appending number 30->>>\n");
    append(l, 30);
    print_list(l);
    printf("list_len = %d\n", list_len(l));
    printf("\n<<<-Removing first element of the list->>>\n");
    drop_begin(l);
    print_list(l);
    printf("list_len = %d\n", list_len(l));
    printf("\n<<<-Removing first element of the list->>>\n");
    drop_begin(l);
    print_list(l);
    printf("list_len = %d\n", list_len(l));
    printf("\n<<<-Removing first element of the list->>>\n");
    drop_begin(l);
    print_list(l);
    printf("list_len = %d\n", list_len(l));
    printf("\n<<<-Appending elements in the list l->>>\n");
    for (i = 0; i <= 100; i += 10) append(l, i);
    print_list(l);
    printf("\n<<<-Removing an element->>>\n");
    printf("return of remove_value(l, 0) = %d\n", remove_value(l, 0));
    print_list(l);
    printf("\n<<<-Removing an element->>>\n");
    printf("return of remove_value(l, 100) = %d\n", remove_value(l, 100));
    print_list(l);
    printf("\n<<<-Removing an element->>>\n");
    printf("return of remove_value(l, 45) = %d\n", remove_value(l, 45));
    print_list(l);
    printf("\n<<<-Removing an element->>>\n");
    printf("return of remove_value(l, 40) = %d\n", remove_value(l, 40));
    print_list(l);
    printf("\n<<<-Cleaning list l->>>\n");
    print_list(l); 
    clear_list(l);
    print_list(l);
    printf("\n<<<-Removing an element from an empty list->>>\n");
    printf("return of remove_value(l, 40) = %d\n", remove_value(l, 40));
    print_list(l);
    printf("\n<<<-Checking if the l is empity->>>\n");
    print_list(l);
    printf("return of its_empty(l) = %d\n", its_empty(l));
    printf("\n<<<-Checking if the l is empity->>>\n");
    append(l, 10);
    print_list(l);
    printf("return of its_empty(l) = %d\n", its_empty(l));
    printf("\n<<<-Removing the last element from l->>>\n");
    drop_begin(l);
    print_list(l);
    printf("return of the remove_last(l) = %d\n", remove_last(l));
    print_list(l);
    printf("\n<<<-Removing the last element from l->>>\n");
    append(l, 10);
    print_list(l);
    printf("return of the remove_last(l) = %d\n", remove_last(l));
    print_list(l);
    printf("\n<<<-Removing the last element from l->>>\n");
    append(l, 10);
    append(l, 20);
    print_list(l);
    printf("return of the remove_last(l) = %d\n", remove_last(l));
    print_list(l);
    //printf("\n<<<-Appending elements in the list l->>>\n");
    drop_begin(l);
    printf("\n<<<-Has element->>>\n");
    print_list(l);
    printf("return of has_element(l, 0) = %d\n", has_element(l, 0));
    printf("\n<<<-Has element->>>\n");
    append(l, 0);
    print_list(l);
    printf("return of has_element(l, 0) = %d\n", has_element(l, 0));
    printf("\n<<<-Has element->>>\n");
    print_list(l);
    printf("return of has_element(l, 125) = %d\n", has_element(l, 125));
    drop_begin(l);
    for (i = 0; i <= 100; i += 10) append(l, i);
    //print_list(l);
    printf("\n<<<-Has element->>>\n");
    print_list(l);
    printf("return of has_element(l, 0) = %d\n", has_element(l, 0));
    printf("\n<<<-Has element->>>\n");
    print_list(l);
    printf("return of has_element(l, 100) = %d\n", has_element(l, 100));
    printf("\n<<<-Has element->>>\n");
    print_list(l);
    printf("return of has_element(l, 45) = %d\n", has_element(l, 45));
    printf("\n<<<-Has element->>>\n");
    print_list(l);
    printf("return of has_element(l, 10) = %d\n", has_element(l, 10));
    printf("\n<<<-Inserting an element by position->>>\n");
    print_list(l);
    printf("return of insert_position(l,111,30) = %d\n", insert_position(l,111,30));
    print_list(l);
    printf("\n<<<-Inserting an element by position->>>\n");
    print_list(l);
    printf("return of insert_position(l,111,4) = %d\n", insert_position(l,111,4));
    print_list(l);
    printf("\n<<<-Inserting an element by position->>>\n");
    print_list(l);
    printf("return of insert_position(l,111,0) = %d\n", insert_position(l,111,0));
    print_list(l);
    printf("\n<<<-Inserting an element by position->>>\n");
    print_list(l);
    printf("return of insert_position(l,111,1) = %d\n", insert_position(l,111,1));
    print_list(l);
    clear_list(l);
    printf("\n<<<-Inserting an element by position->>>\n");
    print_list(l);
    printf("return of insert_position(l,222,0) = %d\n", insert_position(l,222,0));
    print_list(l);
    printf("\n<<<-Inserting an element by position->>>\n");
    print_list(l);
    printf("return of insert_position(l,222,1) = %d\n", insert_position(l,222,1));
    print_list(l);
    printf("\n<<<-Inserting an element by position->>>\n");
    clear_list(l);
    for (i = 0; i <= 100; i += 10) append(l, i);
    print_list(l);
    printf("return of insert_position(l,333,10) = %d\n", insert_position(l,333,10));
    print_list(l);
    printf("\n<<<-Inserting an element by position->>>\n");
    print_list(l);
    printf("return of insert_position(l,333,12) = %d\n", insert_position(l,333,12));
    print_list(l);
    clear_list(l);
    for (i = 0; i <= 100; i += 10) append(l, i);
    printf("\n<<<-Removing elements by position->>>\n");
    print_list(l);
    printf("return of remove_position(l, 10) = %d\n", remove_position(l, 10));
    print_list(l);
    printf("\n<<<-Removing elements by position->>>\n");
    print_list(l);
    printf("return of remove_position(l, 0) = %d\n", remove_position(l, 0));
    print_list(l);
    printf("\n<<<-Removing elements by position->>>\n");
    print_list(l);
    printf("return of remove_position(l, 100) = %d \n", remove_position(l, 100));
    print_list(l);
    printf("\n<<<-Removing elements by position->>>\n");
    print_list(l);
    printf("return of remove_position(l, 7) = %d\n", remove_position(l, 7));
    print_list(l);
    int vret;
    int* p = &vret;
    printf("\n<<<-Geting a value for the vret->>>\n");
    print_list(l);
    printf("return of get(l, p, 0) = %d\n", get(l, p, 0));
    printf("vret = %d\n", vret);
    printf("\n<<<-Geting a value for the vret->>>\n");
    print_list(l);
    printf("return of get(l, p, 7) = %d\n", get(l, p, 7));
    printf("vret = %d\n", vret);
    printf("\n<<<-Geting a value for the vret->>>\n");
    print_list(l);
    printf("return of get(l, p, 4) = %d\n", get(l, p, 4));
    printf("vret = %d\n", vret);
    printf("\n<<<-Geting a value for the vret->>>\n");
    print_list(l);
    printf("return of get(l, p, 15) = %d\n", get(l, p, 15));
    printf("vret = %d\n", vret);
    return 0;
}